services:
  postgres:
    image: postgres:latest
    container_name: 'postgres'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  aplicacao:
    restart: unless-stopped
    build:
      dockerfile: aplicacao.dockerfile
      context: .
    container_name: 'aplicacao'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres
      SERVER_PORT: 8443
      TJULIOH_ALLOWED_ORIGINS: http://localhost:4200
    ports:
      - '8443:8443'
    volumes:
      - 'aplicacao:/tmp'
volumes:
  postgres:
  aplicacao:
